Pull up to arbor master and add CI
arbor-sim/nsuite pull request #113
Opened 2022-03-21 13:47 UTC by thorstenhater

2022-04-06 11:24 UTC, noraabiakar reviewed
Looks good! Thanks. Just one small question

2022-04-06 11:24 UTC, noraabiakar commented on install-local.sh
> +# export CXX="$ns_cxx"
Are these meant to stay commented?

2022-04-06 17:34 UTC, thorstenhater commented on install-local.sh
> +# export CXX="$ns_cxx"
Probably not, but I had specific issues with it on Juwels. I'll revert it and fix as it comes back up.

2022-04-27 13:12 UTC, thorstenhater commented on install-local.sh
> +# export CXX="$ns_cxx"
Done @noraabiakar

2022-05-25 11:13 UTC, brenthuisman requested changes
To avoid issues with shifting ~~sands~~submodules, cloning the requested tag instead of master will help (or was this solved another way?).

In `build_arbor.sh` to `git clone --depth 1 --branch <tag_name> <repo_url>`.

2022-06-27 14:38 UTC, merged